### ISSUE TITLE
No allowed presets for OVC+RA. Defaulting to CLR

### ISSUE THREAD

**Issue by dschigt** [evogelsa/DCS-real-weather#21]
Hi all,

Today I attempted to use RealWeather. Upon my attempt to include a METAR, I get next error:

No allowed presets for OVC+RA. Defaulting to CLR

Any clue what is happening and/or what I am doing wrong? The METAR in itself seems fine and nicely representing the weather, at that moment in time.
See also attached log file from RealWeather applicationl.
[logfile.log](https://github.com/evogelsa/dcs-real-weather/files/13478970/logfile.log)

Thanks for any clarification and/or support.

Best regards,

Detlev Schigt

**Comment by evogelsa** [comment]
If you're using the default provided config.json, there should be a section that looks like this:

```json
    "clouds": {
      "disallowed-presets": [
        "RainyPreset1",
        "RainyPreset2",
        "RainyPreset3"
      ]
    },
```

Remove the options in "disallowed-presets" so that it looks like this:

```json
    "clouds": {
      "disallowed-presets": [
      ]
    },
```

That will allow all of the weather presets to be used. What was happening is that your METAR reported rain but the only DCS weather presets with rain as an option were disallowed by your config, so RealWeather uses its default weather (clear skies).

**Comment by dschigt** [comment]
Hi Ethan,

Thanks for the quick reply. Let me attempt this, assuming it is going to work. Thanks again :-)

Best regards,

Detlev Schigt
