### ISSUE TITLE
TLS error on connecting to CheckWX

### ISSUE THREAD

**Issue by jojom4n** [evogelsa/dcs-real-weather#50]
**Describe the bug**
Logfile warns about a TLS error fetching data from CheckWX

2024/12/16 00:07:30 Error getting weather, using default: Error making request to CheckWX: Get "https://api.checkwx.com/metar/LTDA/decoded": remote error: tls: internal error

**Expected behavior**
I should be able to fetch data from CheckWX

**Comment by evogelsa** [comment]
`remote error: tls: internal error` suggests a TLS issue on the server side (CheckWX) and is not a client issue (your computer/real weather). This was likely caused by a temporary CheckWX outage of some sort. The only thing you can do client side is enable the fallback providers (if using v2.0.0-beta-1 or later) that will use a different API like aviationweather.gov if CheckWX is inoperative.
